<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>8167e04a-4f22-4239-a6c2-346cea57b5fa</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinancialHelper.ApiService\FinancialHelper.ApiService.csproj" />
    <ProjectReference Include="..\FinancialHelper.Web\FinancialHelper.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.3.0" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="9.3.0" />
  </ItemGroup>

</Project>
